from sqlalchemy import create_engine, Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import declarative_base, sessionmaker, relationship
from datetime import datetime
import os

from sqlalchemy import event
from sqlalchemy.engine import Engine

DATABASE_URL = os.environ.get("DATABASE_URL", "sqlite:///./chat.db")

engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False, "timeout": 30})

@event.listens_for(Engine, "connect")
def set_sqlite_pragma(dbapi_connection, connection_record):
    cursor = dbapi_connection.cursor()
    cursor.execute("PRAGMA journal_mode=WAL")
    cursor.execute("PRAGMA synchronous=NORMAL")
    cursor.close()

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

class ChatSession(Base):
    __tablename__ = "sessions"
    
    id = Column(String, primary_key=True, index=True)
    title = Column(String, default="New Chat")
    created_at = Column(DateTime, default=datetime.utcnow)
    
    messages = relationship("ChatMessage", back_populates="session", cascade="all, delete-orphan")

class ChatMessage(Base):
    __tablename__ = "messages"
    
    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(String, ForeignKey("sessions.id"))
    role = Column(String) # 'user' or 'model'
    content = Column(Text)
    redacted_types = Column(Text, nullable=True) # JSON list of dicts
    created_at = Column(DateTime, default=datetime.utcnow)
    
    session = relationship("ChatSession", back_populates="messages")

class UserConfig(Base):
    __tablename__ = "user_configs"
    
    user_id = Column(String, primary_key=True, index=True)
    tier_block = Column(Text, default="[]") # JSON list
    tier_redact = Column(Text, default="[]") # JSON list
    tier_audit = Column(Text, default="[]") # JSON list

class StatLog(Base):
    __tablename__ = "stat_logs"
    
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, index=True)
    session_id = Column(String)
    action = Column(String) # BLOCK, REDACT, AUDIT, CLEAN
    detected_types = Column(Text) # JSON list
    flagged_sequences = Column(Text, default="[]") # JSON list of the actual flagged words
    original_message = Column(Text, nullable=True) # Raw user message for Block/Redact
    created_at = Column(DateTime, default=datetime.utcnow)

class CustomLabel(Base):
    __tablename__ = "custom_labels"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True, index=True)
    description = Column(Text)
    tier = Column(String) # BLOCK, REDACT, AUDIT
    regex_pattern = Column(String, nullable=True) # Generated by LLM
    dictionary_words = Column(Text, default="[]") # JSON list of specific terms
    created_at = Column(DateTime, default=datetime.utcnow)

def init_db():
    Base.metadata.create_all(bind=engine)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
